Fazendo a validacao do metodo Post do Contronle, porém não validando …
Alexandrehs/customer pull request #1
Opened 2021-04-02 01:50 UTC by Alexandrehs

Fala Thiago bele, ou ele não está fazendo a validação de tipo no cpf min e max de 11, somente de notblank.

2021-04-02 14:29 UTC, thiagohnunes requested changes

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>  import org.springframework.web.bind.annotation.*
Remover import genérico. Configure sua ide para te auxiliar.
`File/Settings/Editor/Code Style/Kotlin/` Selecione a aba `imports` e marque as opções `Use Single Name Import`

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
> +@Validated
Qual objetivo da annotation `@Validated` aqui?

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>    @PostMapping("/add")
Pensando nos principios do Rest, esse `/add` deveria existir?

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>  }
Esse simbolo está aqui porque o github está pedindo que você termine o arquivo com uma linha em branco.

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/models/CustomerModel.kt
>  import javax.persistence.*
Remova o import genérico.

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>      return customer
O método vai retornar todos os dados? A princípio está mapeado apena o id, certo?

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
> +  fun add(@RequestBody @Valid customer: Customer) : Customer {
Você vai receber na request os dados na mesma estrutura que persiste? 
E vai retornar essa mesma estrutura também? 

O que quero dizer é: Você está usando a mesma estrutura para coisas diferentes, além de expôr sua estrutura de banco para quem consome a API.
Minha sugestão é a partir de agora dividir as coisas, as responsabilidades.
Customer deve ser até agora:

`CustomerRequest`: para representar a request
`CustomerResponse`: para representar a resposta
`CustomerEntity`: Para representar o banco. Mas para esse momento, não vamos trabalhar com persistência ainda.

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/models/CustomerModel.kt
>  @Entity
Eu não adicionaria as validações nessa classe. Eu criaria uma classe CustomerRequest para representar o payload de request e nela eu faria as validações.

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/models/CustomerModel.kt
> +  val cpf: String,
Se o usuário passar um CPF inválido? Essas validações resolveriam o problema?

2021-04-02 14:29 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/models/CustomerModel.kt
> +  val cep: String,
Quantos caracteres possui um cep? Se o usuário passar 384121068987 ou 4646464ABC464 ou 464646#*&*AA5 sua validação vai barrar?

2021-04-02 15:02 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>  import org.springframework.web.bind.annotation.*
ok

2021-04-02 15:03 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
> +@Validated
Vi isso em alguns tutoriais, achei que ia resolver o meu problema de não está aplicando as anotations do validate, coloquei pra ver mas não adiantou kk, ja removi

2021-04-02 15:36 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>    @PostMapping("/add")
Hum, verdade pois o método Post já indica que haverá uma inserção do controller ne.

2021-04-02 15:37 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/models/CustomerModel.kt
>  import javax.persistence.*
ok

2021-04-02 15:39 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>      return customer
Verdade você me pediu para retorna apenas o ID. Feito

2021-04-02 15:42 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
> +  fun add(@RequestBody @Valid customer: Customer) : Customer {
Bom seria então ao invés de ter um Controller que faz as requests e responses, eu divida isso como você está sugerindo, CustomerRequest onde haverá todos os métodos de request junto com as validações, CustomerResponse onde retornaremos dados, é isso?

2021-04-05 03:34 UTC, thiagohnunes approved these changes

2021-04-05 21:48 UTC, merged