Exceptions
Alexandrehs/customer pull request #2
Opened 2021-04-04 16:58 UTC by Alexandrehs

Consegui fazer voltar mensagens amigaveis passadas no Payload CustomerController, porem, sendo sincero entendi a logica mas nao o conceito e o porque de cada coisa kkk entedeu?

2021-04-07 01:31 UTC, thiagohnunes requested changes

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
>  import org.springframework.web.bind.annotation.*
Não use import genérico.

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
> +import java.util.*
Import genérico

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/exceptions/CustomerException.kt
> +data class CustomerException(
Os atributos dessa classe deveriam ser mapeados com (?)? Acredito que não. E por qual motivo está inicializando os mesmos?

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/controllers/CustomerController.kt
> + @ExceptionHandler(MethodArgumentNotValidException::class)
Por enquanto podemos deixar esse código de interceptar a exception aqui. Depois vamos refatorar e mover para uma local mais adequado.

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +import javax.persistence.Id
Anotação desnecessária.

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +  @field:NotBlank(message = "Desculpe, o nome não pode ficar em branco.", )
Não curti o padrão das mensagens. Apenas seja direto.
Ex:
 O nome não deve conter caracteres em branco.

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +  @field:Size(min = 10, max = 50, message = "Desculpe, o nome deve conter no minimo 10 letras.")
Mesma coisa, coloque algo como:
Quantidade de caracteres invalida para o nome.

O problema é que, mesmo sendo direto, não fala para quem está consumindo a API o que fazer. Você pode usar parametros na mensagem tipo:

Nome deve ter entre {min} e {max} caracteres.

2021-04-07 01:31 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +  val id: String?
Esse cara precisa ser nullable? É necessário o ? aqui?

2021-04-07 08:25 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/exceptions/CustomerException.kt
> +data class CustomerException(
Você tem razão, foi descuido meu quando estava tentando resolver o problema estava me pedindo pra inicializa-los, porém, depois de encontra a solução correta esqueci de remove-los.

2021-04-08 18:03 UTC, thiagohnunes commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +  val id: String?
Esse atributo não precisa ser nullable.

2021-04-09 15:37 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +import javax.persistence.Id
retirado.

2021-04-09 15:37 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +  @field:Size(min = 10, max = 50, message = "Desculpe, o nome deve conter no minimo 10 letras.")
feito

2021-04-09 15:38 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +  val id: String?
acredito que por enquanto precisa visto que retornamos ele.

2021-04-09 15:38 UTC, Alexandrehs commented on src/main/kotlin/br/com/estudante/customerapi/rest/Payload.kt
> +  @field:NotBlank(message = "Desculpe, o nome não pode ficar em branco.", )
feito

2021-04-09 16:09 UTC, thiagohnunes approved these changes

2021-04-10 08:16 UTC, merged