Postgresql flyway
Alexandrehs/customer pull request #8
Opened 2021-04-19 10:02 UTC by Alexandrehs

Implementei o flyway, confere por favor se estar correto.

2021-04-30 23:47 UTC, thiagohnunes requested changes

2021-04-30 23:47 UTC, thiagohnunes commented on src/main/resources/application.yml
> +    generate-ddl: true
Remova essa configuração. Vamos usar o flyway para gerenciar as versões do banco de dados

2021-04-30 23:47 UTC, thiagohnunes commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    id VARCHAR(244) NOT NULL PRIMARY KEY,
Como vamos usar UUID para o ID, acho desnecessário um varchar de 244. Veja qual tamanho de um UUID e coloque um tamanho mais adequado.

2021-04-30 23:47 UTC, thiagohnunes commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    name VARCHAR(100) NOT NULL,
Na request o tamanho máximo do atributo nome é 50 posições e aqui vc está criando com tamanho 100. Existe um motivo?

2021-04-30 23:47 UTC, thiagohnunes commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    email VARCHAR(244) NOT NULL,
Esse tamanho de 244 é necessário para o email? Só questionando!

2021-04-30 23:50 UTC, Alexandrehs commented on src/main/resources/application.yml
> +    generate-ddl: true
Feito foi removido

2021-04-30 23:52 UTC, Alexandrehs commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    id VARCHAR(244) NOT NULL PRIMARY KEY,
Foi modificado para 32 caracteres o tamanho gerado pelo UUID

2021-04-30 23:52 UTC, Alexandrehs commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    name VARCHAR(100) NOT NULL,
Não foi uma falha mesmo, ja foi alterado

2021-04-30 23:53 UTC, Alexandrehs commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    email VARCHAR(244) NOT NULL,
Bom para garantir que o email da pessoa caiba.

2021-05-01 00:30 UTC, thiagohnunes requested changes

2021-05-01 00:30 UTC, thiagohnunes commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    email VARCHAR(244) NOT NULL,
Essa virgula no final vai dar erro. Remova

2021-05-01 00:30 UTC, thiagohnunes commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    id VARCHAR(244) NOT NULL PRIMARY KEY,
O diretorio do arquivo está errado. Coloque `migration` em vez de `migrations`

2021-05-01 20:06 UTC, Alexandrehs commented on src/main/resources/db/migrations/V1__create-table-customers.sql
> +    id VARCHAR(244) NOT NULL PRIMARY KEY,
ja foi removido

2021-05-01 20:31 UTC, merged